### ISSUE TITLE
Bypass signature check of QQ 9.0.60

### ISSUE THREAD

**Issue by kmod-midori** [JingMatrix/LSPatch#8] opened 2024-09-11 15:55 UTC
### Steps to reproduce/复现步骤

1. Patch QQ 9.0.60 6478 with integrated mode, without any module.
2. Launch the patched application and attempt to login.

### Expected behaviour/预期行为

Application should launch and run without any issues (just like in upstream LSPatch)

### Actual behaviour/实际行为

Application launches, but logging into any account fails:
```
com.tencent.mobileqq.msf.service.MsfService timeout
```

### Xposed Module List/Xposed 模块列表

```Shell
N/A
```

### LSPatch version/LSPatch 版本

CI build b409cd3 (debug)

### Android version/Android 版本

14 with August Google system update (QPR3)

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[qq_filtered.log](https://github.com/user-attachments/files/16966235/qq_filtered.log)

**Comment by JingMatrix** [comment] 2024-09-11 16:03
Could you please try some other builds in the GitHub Actions and tell me if some of them work fine with you?

**Comment by kmod-midori** [comment] 2024-09-11 16:05
Which versions shoud I try? Currently I know that the `libart.so` on my device is stripped and incompatible with upstream LSPlant.

**Comment by JingMatrix** [comment] 2024-09-11 16:42
This one please: https://github.com/JingMatrix/LSPatch/actions/runs/10236530167

**Comment by kmod-midori** [comment] 2024-09-12 01:04
[qq_b8c4664_filt.log](https://github.com/user-attachments/files/16971935/qq_b8c4664_filt.log)
No initial crash (the first launch works), but still can't login due to that native crash.

**Comment by JingMatrix** [comment] 2024-09-12 10:58
Please try the latest build to see if the issue still exists.

**Comment by kmod-midori** [comment] 2024-09-12 14:23
44f5a12 does not launch at all :(

[qq_44f5a12_filt_no_mod.log](https://github.com/user-attachments/files/16980980/qq_44f5a12_filt_no_mod.log)

**Comment by JingMatrix** [comment] 2024-09-12 16:09
> 44f5a12 does not launch at all :(

This seems to be a build bug of CI, see https://github.com/JingMatrix/LSPosed/issues/30. My local build works well.

**Comment by JingMatrix** [comment] 2024-09-12 16:48
@mario6714 Here is a local build from my machine.
[localDebug.zip](https://github.com/user-attachments/files/16982913/localDebug.zip)

**Comment by JingMatrix** [comment] 2024-09-12 17:13
The build bug should be fixed by the latest commit. Please try it from GitHub Actions.

**Comment by JingMatrix** [comment] 2024-09-12 19:50
@mario6714 check that you patch and embed modules correctly. If you still have the problem, open a new issues with logs (you may ask Google or AI about how to use `adb` to save logs.)
Current issue is not related to your problem.

**Comment by kmod-midori** [comment] 2024-09-13 00:59
2681111 has the exact same error. 
[qq_2681111_filt.log](https://github.com/user-attachments/files/16987146/qq_2681111_filt.log)

**Comment by JingMatrix** [comment] 2024-09-13 06:41
@kmod-midori Are you sure that you didn't embed any modules? From the log, it seems that you at least used a module using `native_api`.

**Comment by kmod-midori** [comment] 2024-09-13 06:52
[qq_2681111_filt2.log](https://github.com/user-attachments/files/16989672/qq_2681111_filt2.log)
No difference with or without a module.

**Comment by JingMatrix** [comment] 2024-09-13 07:00
@kmod-midori Could you please try TIM to see if LSPatch works with it ?

**Comment by kmod-midori** [comment] 2024-09-13 07:09
[tim_2681111_filt.log](https://github.com/user-attachments/files/16989832/tim_2681111_filt.log)
No luck, crashes in the same way (and more).

**Comment by JingMatrix** [comment] 2024-09-13 07:15
This bug should be related to the signature by pass
```
09-13 14:51:18.935 16480 16480 D LSPosed : elf_util.cpp:365#Elf64_Addr SandHook::ElfImg::getSymbOffset(std::string_view, uint32_t, uint32_t) const: found __openat 0xaefc0 in /apex/com.android.runtime/lib64/bionic/libc.so in symtab by linear lookup
09-13 14:51:18.936 16480 16480 D LSPosed : native_api.h:62#int lspd::HookInline(void *, void *, void **): Dobby hooking (unknown symbol) (0x7b5eb1afc0) from /apex/com.android.runtime/lib64/bionic/libc.so (0x7b5ea6c000)
09-13 14:51:18.936 16480 16480 D LSPosed : bypass_sig.cpp:49#void lspd::Java_org_lsposed_lspd_nativebridge_SigBypass_enableOpenatHook(JNIEnv *, jclass, jstring, jstring): apkPath %s
09-13 14:51:18.936 16480 16480 D LSPosed : bypass_sig.cpp:50#void lspd::Java_org_lsposed_lspd_nativebridge_SigBypass_enableOpenatHook(JNIEnv *, jclass, jstring, jstring): redirectPath %s
09-13 14:51:18.936 16480 16480 I LSPatch : LSPatch bootstrap completed
```

The crash happens after
```
09-13 14:51:19.331 16480 16480 D LSPatch-SigBypass: Replace signature info for `com.tencent.mobileqq` (method 1)
```

It should be that `__openat` function is not correctly hooked.

**Comment by JingMatrix** [comment] 2024-09-13 07:26
@kmod-midori Please upload your `libc.so` file using
```
adb pull /apex/com.android.runtime/lib64/bionic/libc.so
```
GitHub might require you to zip it first.

**Comment by JingMatrix** [comment] 2024-09-13 07:32
If there is a LSPatch version that works with QQ, please also upload the logs of it.
Did you claim that the upstream LSPatch works for you?

**Comment by kmod-midori** [comment] 2024-09-13 07:47
[libc.zip](https://github.com/user-attachments/files/16990321/libc.zip)
Upstream LSPatch only worked before the ART system update, I have it available on another OneUI device, but I can't clear data or remove modules because it is in use, do you still need the log?

**Comment by JingMatrix** [comment] 2024-09-13 07:55
I see. To temporarily solve this problem, when you patch QQ, please chose a different signature bypass level.
Currently, the signature bypass level 2 doesn't work properly.

**Comment by JingMatrix** [comment] 2024-09-13 10:51
I have pushed new commits, please try it from the latest CI and post your logs. Thanks!

**Comment by JingMatrix** [comment] 2024-09-13 11:47
> I see. To temporarily solve this problem, when you patch QQ, please chose a different signature bypass level. Currently, the signature bypass level 2 doesn't work properly.

I tried signature bypass level 1, and it works with TIM login.

**Comment by kmod-midori** [comment] 2024-09-13 14:28
[qq_2325e7a_filt_no_mod.log](https://github.com/user-attachments/files/16995098/qq_2325e7a_filt_no_mod.log)
[qq_2325e7a_filt_no_mod_lv1.log](https://github.com/user-attachments/files/16995271/qq_2325e7a_filt_no_mod_lv1.log)

Lv1 does not work for QQ. The paths does not look wrong to me. My concern is that if they are really reading the APK file for security reasons, could this pose a risk to users' accounts?

**Comment by JingMatrix** [comment] 2024-09-13 14:42
I think they are using new ways of checking signature, which are not handled by LSPatch yet.
I recommend you to use the QQ from Google Play store, which works well with LSPatch as I tested.

**Comment by JingMatrix** [comment] 2024-09-13 14:49
Wait, this is not a bug of LSPatch.
The crash of MSF services happens even with the original APK.

**Closed by JingMatrix** 2024-09-13 14:49 UTC
Labels: bug

**Comment by kmod-midori** [comment] 2024-09-13 15:03
Well, it seem that the ART update broke QQ instead of LSPatch...
